import type { NewsItem, StateData } from './types'

export const MOCK_NEWS: NewsItem[] = [
  { id: '1', title: 'NDRF teams deployed in flood-affected districts of Assam', description: 'National Disaster Response Force has deployed 15 teams to assist in rescue operations following heavy rainfall.', source: 'NDRF', sourceType: 'NDRF', url: 'https://ndrf.gov.in', publishedAt: new Date().toISOString(), state: 'Assam', threatLevel: 'high', threatConfidence: 0.88, threatCategory: 'Natural Disaster' },
  { id: '2', title: 'CERT-In alerts on critical vulnerability in enterprise software', description: 'Indian Computer Emergency Response Team has issued advisory CERT-In/2026/01 for a critical remote code execution vulnerability.', source: 'CERT-In', sourceType: 'CERT-In', url: 'https://cert-in.org.in', publishedAt: new Date(Date.now() - 3600000).toISOString(), threatLevel: 'critical', threatConfidence: 0.95, threatCategory: 'Cyber' },
  { id: '3', title: 'IMD issues cyclone warning for Bay of Bengal — Odisha and Andhra Pradesh on alert', description: 'India Meteorological Department has issued a yellow alert for coastal districts. Fishermen advised not to venture into sea.', source: 'IMD', sourceType: 'IMD', url: 'https://mausam.imd.gov.in', publishedAt: new Date(Date.now() - 7200000).toISOString(), state: 'Odisha', threatLevel: 'high', threatConfidence: 0.91, threatCategory: 'Natural Disaster' },
  { id: '4', title: 'PIB: Cabinet approves Rs 5000 crore for border infrastructure development', description: 'The Union Cabinet chaired by Prime Minister approved strengthening of border infrastructure in Northeast India.', source: 'PIB', sourceType: 'PIB', url: 'https://pib.gov.in', publishedAt: new Date(Date.now() - 10800000).toISOString(), threatLevel: 'low', threatConfidence: 0.72, threatCategory: 'Border' },
  { id: '5', title: 'Kerala high court orders monitoring of dam water levels amid heavy rainfall', description: 'Following continuous heavy rainfall in Western Ghats, water levels at Idukki dam have reached 80% capacity.', source: 'DD News', sourceType: 'DD News', url: 'https://ddnews.gov.in', publishedAt: new Date(Date.now() - 14400000).toISOString(), state: 'Kerala', threatLevel: 'medium', threatConfidence: 0.79, threatCategory: 'Natural Disaster' },
  { id: '6', title: 'CERT-In: Phishing campaign targeting Indian banking customers detected', description: 'Multiple phishing emails impersonating nationalised banks have been detected. Citizens advised to verify before clicking links.', source: 'CERT-In', sourceType: 'CERT-In', url: 'https://cert-in.org.in', publishedAt: new Date(Date.now() - 18000000).toISOString(), threatLevel: 'medium', threatConfidence: 0.83, threatCategory: 'Cyber' },
  { id: '7', title: 'Uttarakhand: Landslide blocks NH-58 near Chamoli, NDRF on standby', description: 'A major landslide has blocked National Highway 58 near Chamoli district. NDRF teams have been put on standby alert.', source: 'NDRF', sourceType: 'NDRF', url: 'https://ndrf.gov.in', publishedAt: new Date(Date.now() - 21600000).toISOString(), state: 'Uttarakhand', threatLevel: 'high', threatConfidence: 0.87, threatCategory: 'Natural Disaster' },
  { id: '8', title: 'PIB: India launches 5G emergency communication network for disaster response', description: 'Department of Telecommunications launched a dedicated 5G network for first responders and disaster management teams across 28 states.', source: 'PIB', sourceType: 'PIB', url: 'https://pib.gov.in', publishedAt: new Date(Date.now() - 25200000).toISOString(), threatLevel: 'safe', threatConfidence: 0.92, threatCategory: 'General' },
]

export const INDIA_STATES: StateData[] = [
  { name: 'Jammu & Kashmir', code: 'JK', threatLevel: 'medium', alertCount: 3, lat: 34.0, lng: 76.0 },
  { name: 'Himachal Pradesh', code: 'HP', threatLevel: 'low', alertCount: 1, lat: 31.1, lng: 77.2 },
  { name: 'Punjab', code: 'PB', threatLevel: 'low', alertCount: 2, lat: 31.1, lng: 75.3 },
  { name: 'Uttarakhand', code: 'UK', threatLevel: 'high', alertCount: 5, lat: 30.3, lng: 78.0 },
  { name: 'Haryana', code: 'HR', threatLevel: 'low', alertCount: 1, lat: 29.0, lng: 76.1 },
  { name: 'Delhi', code: 'DL', threatLevel: 'medium', alertCount: 4, lat: 28.6, lng: 77.2 },
  { name: 'Rajasthan', code: 'RJ', threatLevel: 'low', alertCount: 2, lat: 27.0, lng: 74.2 },
  { name: 'Uttar Pradesh', code: 'UP', threatLevel: 'medium', alertCount: 6, lat: 26.8, lng: 80.9 },
  { name: 'Bihar', code: 'BR', threatLevel: 'medium', alertCount: 3, lat: 25.0, lng: 85.3 },
  { name: 'Sikkim', code: 'SK', threatLevel: 'low', alertCount: 1, lat: 27.5, lng: 88.5 },
  { name: 'Arunachal Pradesh', code: 'AR', threatLevel: 'medium', alertCount: 2, lat: 27.1, lng: 93.6 },
  { name: 'Nagaland', code: 'NL', threatLevel: 'low', alertCount: 1, lat: 26.1, lng: 94.6 },
  { name: 'Manipur', code: 'MN', threatLevel: 'high', alertCount: 7, lat: 24.6, lng: 93.9 },
  { name: 'Mizoram', code: 'MZ', threatLevel: 'low', alertCount: 1, lat: 23.1, lng: 92.9 },
  { name: 'Tripura', code: 'TR', threatLevel: 'low', alertCount: 2, lat: 23.7, lng: 91.7 },
  { name: 'Meghalaya', code: 'ML', threatLevel: 'medium', alertCount: 3, lat: 25.5, lng: 91.4 },
  { name: 'Assam', code: 'AS', threatLevel: 'high', alertCount: 8, lat: 26.2, lng: 92.9 },
  { name: 'West Bengal', code: 'WB', threatLevel: 'medium', alertCount: 4, lat: 22.9, lng: 87.8 },
  { name: 'Jharkhand', code: 'JH', threatLevel: 'low', alertCount: 2, lat: 23.6, lng: 85.3 },
  { name: 'Odisha', code: 'OR', threatLevel: 'high', alertCount: 6, lat: 20.9, lng: 85.1 },
  { name: 'Chhattisgarh', code: 'CG', threatLevel: 'medium', alertCount: 4, lat: 21.3, lng: 81.8 },
  { name: 'Madhya Pradesh', code: 'MP', threatLevel: 'low', alertCount: 3, lat: 22.9, lng: 78.6 },
  { name: 'Gujarat', code: 'GJ', threatLevel: 'low', alertCount: 2, lat: 22.3, lng: 72.6 },
  { name: 'Maharashtra', code: 'MH', threatLevel: 'medium', alertCount: 5, lat: 19.7, lng: 75.7 },
  { name: 'Goa', code: 'GA', threatLevel: 'safe', alertCount: 0, lat: 15.3, lng: 74.1 },
  { name: 'Karnataka', code: 'KA', threatLevel: 'low', alertCount: 2, lat: 15.3, lng: 75.7 },
  { name: 'Andhra Pradesh', code: 'AP', threatLevel: 'high', alertCount: 5, lat: 15.9, lng: 79.7 },
  { name: 'Telangana', code: 'TG', threatLevel: 'medium', alertCount: 3, lat: 17.4, lng: 78.5 },
  { name: 'Tamil Nadu', code: 'TN', threatLevel: 'low', alertCount: 2, lat: 11.1, lng: 78.7 },
  { name: 'Kerala', code: 'KL', threatLevel: 'medium', alertCount: 4, lat: 10.9, lng: 76.3 },
]
